export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_DETAILS = "PRODUCT_LIST_DETAILS";
export const PRODUCT_LIST_ERROR = "PRODUCT_LIST_ERROR";
export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_DETAILS = "PRODUCT_DETAILS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
